version: '3.4'

services:
  post.api:
    container_name: post.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionString:PostConnectionString=Server=mssql;Database=PostDb;User Id=sa;Password=MATF12345678rs2;"
    depends_on:
      - mssql
    ports:
      - "8001:8080"

  user.api:
    container_name: user.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionString:UserConnectionString=Server=mssql;Database=UserDb;User Id=sa;Password=MATF12345678rs2;"
    depends_on:
      - mssql
    ports:
      - "8002:8080"


  mssql:
    container_name: mssql
    environment:
        - SA_PASSWORD=MATF12345678rs2
        - ACCEPT_EULA=Y
    restart: always
    ports:
        - "1433:1433"
    volumes:
        - mssql_data:/var/opt/mssql/data
