version: '3.4'

services:
  productsdb:
    container_name: productsdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:\data\db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  rewarddb:
    container_name: rewarddb   
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
 
  mssql:
    container_name: mssql
    environment:
        - SA_PASSWORD=MATF12345678rs2
        - ACCEPT_EULA=Y
    restart: always
    ports:
        - "1433:1433"
    volumes:
        - mssql_data:/var/opt/mssql/data

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"    

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:8080"


  post.api:
    container_name: post.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:PostConnectionString=Server=mssql;Database=PostDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=True;Encrypt=False;"
      - "ConnectionStrings:UserServiceUriString=http://user.api:8080/"
      - "ConnectionStrings:RewardServiceUriString=http://reward.api:8080/"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - rabbitmq
      - mssql
      - user.api
      - reward.api
    ports:
      - "8004:8080" 


  user.api:
    container_name: user.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:UserConnectionString=Server=mssql;Database=UserDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=True;Encrypt=False;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - mssql
      - rabbitmq
    ports:
      - "8002:8080"

  reward.api:
    container_name: reward.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=mongodb://rewarddb:27017"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - rewarddb
      - rabbitmq
    ports:
      - "8003:8080"
      
  products.api:
    container_name: products.api
    environment:
      -  ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionSettings=mongodb://productsdb:27017"
    depends_on:
      - productsdb
    ports:
      - "8005:8080"


  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=mssql;Database=OrderDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=True;Encrypt=False;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - mssql
      - rabbitmq
    ports:
      - "8005:8080"

