version: '3.4'

services:
  rewarddb:
    image: mongo

  post.api:
    image: ${DOCKER_REGISTRY-}postapi
    build:
      context: .
      dockerfile: Services/Post/Post.API/Dockerfile

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest

  reward.api:
    image: ${DOCKER_REGISTRY-}rewardapi
    build:
      context: .
      dockerfile: Services/Reward/Reward.API/Dockerfile

volumes:
  mssql_data:
  mongo_data:
