version: '3.4'

services:
  rewarddb:
    image: mongo

  productsdb:
    image: mongo

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  post.api:
    image: ${DOCKER_REGISTRY-}postapi
    build:
      context: .
      dockerfile: Services/Posts/Posts.API/Dockerfile

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest

  reward.api:
    image: ${DOCKER_REGISTRY-}rewardapi
    build:
      context: .
      dockerfile: Services/Reward/Reward.API/Dockerfile

  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Services/Products/Products.API/Dockerfile

volumes:
  mssql_data:
  mongo_data:

