version: '3.4'

services:

  rewarddb:
    container_name: rewarddb   
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionString:BasketConnectionString=Server=mssql;Database=BasketDb;User Id=sa;Password=MATF12345678rs2;"
    depends_on:
      - mssql
    ports:
      - "8001:8080"


  post.api:
    container_name: post.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionString:PostConnectionString=Server=mssql;Database=PostDb;User Id=sa;Password=MATF12345678rs2;"
    depends_on:
      - mssql
    ports:
      - "8001:8080" 


  user.api:
    container_name: user.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionString:UserConnectionString=Server=mssql;Database=UsertDb;User Id=sa;Password=MATF12345678rs2;"
    depends_on:
      - mssql
    ports:
      - "8002:8080"

  reward.api:
    container_name: reward.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=mongodb://rewarddb:27017"
    depends_on:
      - rewarddb
    ports:
      - "8003:8080"

  mssql:
    container_name: mssql
    environment:
        - SA_PASSWORD=MATF12345678rs2
        - ACCEPT_EULA=Y
    restart: always
    ports:
        - "1433:1433"
    volumes:
        - mssql_data:/var/opt/mssql/data

  

