version: '3.4'

services:

  rewarddb:
    image: mongo

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  post.api:
    image: ${DOCKER_REGISTRY-}postapi
    build:
      context: .
      dockerfile: Services/Posts/Posts.API/Dockerfile

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile

  reward.api:
    image: ${DOCKER_REGISTRY-}rewardapi
    build:
      context: .
      dockerfile: Services/Reward/Reward.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
  mssql_data:
  mongo_data:

